using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using FZ.Models;

namespace FZ.Services
{
    public class PostRepository
    {
        private IEnumerable<Post> sqlDbImposter = new Post[]
        {
            new Post
            {
                chapter = 1,
                section = 1,
                perspective = 1,
                content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut pharetra non urna sit amet egestas. Vivamus fringilla aliquam augue vel scelerisque. Pellentesque id diam a mi fringilla accumsan. Integer ornare ex sit amet semper elementum. Vivamus sit amet erat dolor. Aenean quis magna et massa pharetra scelerisque vel at risus. Pellentesque tempor mattis justo, at aliquet sapien elementum non. Praesent et augue efficitur, tincidunt purus quis, aliquet enim. Mauris nec nisi imperdiet, porttitor sem ut, faucibus elit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas." +
"Nam id dui sed mi pharetra condimentum et et est. Duis vestibulum, ante a sollicitudin finibus, lorem lectus rhoncus lectus, a maximus turpis ante vel sem. Quisque accumsan vitae lectus sed iaculis. Quisque quis elit quis eros blandit ultricies a ut nunc. Curabitur placerat bibendum erat sed malesuada. Proin auctor laoreet orci sed suscipit. Maecenas nec mollis eros. Cras velit nisi, scelerisque a nibh a, scelerisque tempor enim. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nulla ut justo eu erat tincidunt viverra et finibus purus. Curabitur viverra lacus id suscipit consectetur. Sed rhoncus hendrerit lorem." +
"Vivamus id egestas sem, quis gravida ante. In risus ligula, vulputate a placerat ut, vehicula dictum lacus. Cras pulvinar, magna eu interdum sollicitudin, lacus augue elementum orci, sit amet luctus massa velit eget dolor. Aliquam eu nibh bibendum, pharetra tellus eget, aliquam mauris. Nunc sed mi et justo sodales laoreet. Vestibulum quis purus neque. Mauris quis felis non odio egestas tincidunt. Nulla rhoncus mauris id ex commodo, at tempus felis aliquet. Morbi dapibus congue leo sed pharetra. Ut non finibus ipsum. Curabitur hendrerit feugiat arcu id sollicitudin." +
"Suspendisse potenti. Quisque a lectus velit. Vestibulum condimentum diam pulvinar purus feugiat vestibulum. Suspendisse vel felis turpis. Aenean ultrices turpis enim, quis eleifend sapien vehicula eget. Integer a velit tortor. Pellentesque iaculis tincidunt felis a aliquet." +
"Integer a pulvinar tellus. Quisque ut maximus felis, vel posuere tortor. Nulla imperdiet diam eget quam congue pellentesque. Pellentesque scelerisque ante ac odio efficitur, vel commodo quam convallis. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas sed leo in enim tempor fringilla et eu purus. Suspendisse dignissim maximus est, a accumsan nisi porttitor eget. Vivamus consectetur imperdiet efficitur. Ut ex enim, imperdiet feugiat quam nec, venenatis convallis augue. Quisque finibus risus eget bibendum mollis." +
"Morbi luctus justo vitae nibh pellentesque, vel malesuada nisl hendrerit. Nulla eget bibendum tellus. Mauris dui nibh, lacinia vitae commodo id, pellentesque ac dui. Morbi vitae ullamcorper sem. Phasellus accumsan commodo ex, nec elementum felis feugiat vitae. Sed eget sapien ut lectus malesuada ullamcorper non vitae est. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam sed facilisis arcu. Morbi imperdiet mi a magna tincidunt, eget bibendum augue hendrerit. In luctus laoreet tortor a tempus. Nam placerat ornare mi non pharetra. Suspendisse tempor ipsum et lorem vulputate vehicula. Maecenas bibendum est lorem, et imperdiet lacus fringilla at." +
"In hac habitasse platea dictumst. Praesent lobortis semper orci a molestie. Nulla facilisi. Maecenas a nisl mollis, finibus lectus at, pharetra enim. Morbi congue, dolor ut facilisis porta, lacus massa fermentum augue, dictum vestibulum metus risus ut arcu. Sed est sapien, scelerisque ac augue eget, convallis tempus lacus. Cras eget malesuada purus. Pellentesque sed arcu suscipit, tincidunt nunc sed, convallis lorem. Aenean viverra nisi accumsan ante maximus, in eleifend elit dapibus. Aliquam nisi tellus, tincidunt ac interdum in, aliquet id libero. Nulla viverra fermentum nulla eget aliquam. Maecenas est sapien, facilisis at imperdiet eget, tristique sit amet enim. Nullam tristique ex ac sapien molestie ultrices. Pellentesque imperdiet sem quis felis maximus, quis sodales felis efficitur. Ut fermentum lobortis diam, nec blandit metus elementum in." +
"Morbi scelerisque aliquam purus, id interdum metus pretium non. Sed id lacinia orci, feugiat convallis quam. Aliquam magna lacus, fringilla porta blandit non, sodales ut enim. Etiam vitae libero sed justo ornare interdum. Nulla non pharetra sem. Aenean efficitur sit amet turpis in ullamcorper. Cras sit amet quam ipsum." +
"Sed ornare ex et dolor rhoncus varius. Donec a est porttitor, maximus neque et, mollis erat. Nunc sagittis viverra vulputate. Vivamus et augue et purus porttitor volutpat sed et lacus. Aliquam scelerisque congue malesuada. Nullam quis sapien eget erat faucibus bibendum. Vivamus vel iaculis massa." +
"Donec congue eros at mauris scelerisque, et varius justo consectetur. Vivamus cursus tempus tellus sed vestibulum. Phasellus quam metus, ultricies sit amet justo in, pulvinar malesuada neque. Sed sem enim, dictum quis arcu vel, suscipit euismod lectus. Fusce lectus mauris, maximus tempus erat quis, pharetra molestie ex. Fusce quis aliquam justo. Sed quis justo volutpat urna volutpat accumsan. Nulla blandit eu orci in auctor. Quisque blandit cursus mi nec facilisis. Nam iaculis mi ut ultricies malesuada. Nulla facilisi."
            },
            new Post
            {
                chapter = 1,
                section = 2,
                perspective = 1,
                content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam laoreet ultrices libero, vel suscipit tortor tincidunt eu. Cras molestie, ex at commodo posuere, odio diam scelerisque augue, eu varius neque sem sit amet sapien. Integer eleifend vel erat id condimentum. Nam lobortis vel neque ac convallis. Nunc tortor enim, tempus in nisi sed, placerat sodales quam. Aenean ante urna, gravida cursus interdum sodales, accumsan ac velit. Ut mollis venenatis massa. Quisque imperdiet ligula et est convallis porttitor. Nulla sit amet neque nec diam commodo lobortis. Mauris sit amet nisi finibus, cursus orci vel, faucibus nunc. Nam maximus massa ex, a bibendum arcu tincidunt sed. Maecenas laoreet, arcu sit amet semper feugiat, massa dui venenatis justo, et eleifend felis nunc nec neque. Fusce ullamcorper nisl quis ullamcorper scelerisque. Etiam faucibus tellus sed velit aliquet, ac venenatis odio laoreet. Donec nec augue id nibh accumsan facilisis efficitur id diam." +
"Proin sit amet felis eget nibh dignissim bibendum vel feugiat ante. Curabitur porta suscipit sapien nec consectetur. Proin sit amet nibh ac massa suscipit sollicitudin. Donec non mauris in tortor sodales placerat ut vel quam. Morbi lobortis nisl in lacus varius cursus. Curabitur vitae euismod enim, aliquam dictum arcu. Praesent lobortis nulla at arcu pretium elementum. Duis vestibulum turpis eu ullamcorper fringilla. Suspendisse porttitor nisl iaculis purus consectetur, et ornare sem fringilla. Pellentesque sit amet est orci. Quisque ante eros, gravida nec ipsum at, finibus mollis mauris. Integer faucibus lacinia est, sit amet facilisis mauris auctor et." +
"Praesent pharetra libero et urna tincidunt, at venenatis ex maximus. Praesent facilisis blandit urna at vestibulum. Fusce et cursus diam. Vestibulum nisi lorem, molestie vitae lorem nec, rhoncus maximus enim. Sed cursus aliquet arcu in hendrerit. Ut vestibulum feugiat ante, dapibus sagittis tellus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Morbi metus orci, cursus eu est at, vulputate egestas dui. Vestibulum in varius metus." +
"Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Proin feugiat finibus neque ut tempus. Mauris volutpat magna urna, et luctus urna facilisis et. Praesent dignissim id risus sit amet laoreet. Etiam quis dapibus lorem. Nunc posuere magna augue, et bibendum elit sagittis sed. Mauris at odio congue, volutpat nibh vitae, mollis arcu. In vel lacus vulputate, luctus purus ac, finibus lacus. Vivamus varius mi magna, vitae suscipit elit vulputate in. Aenean sed ligula mattis, faucibus odio et, rutrum lacus. Integer scelerisque condimentum odio, a tempor tortor lobortis non." +
"Fusce pretium nisi scelerisque velit ultrices cursus. Aliquam dolor turpis, auctor vitae massa vel, gravida tincidunt leo. Fusce aliquet tellus a rutrum convallis. Praesent lacus sapien, mattis ut mi fringilla, porttitor eleifend velit. Aenean tincidunt purus ac dui posuere egestas. Suspendisse egestas rhoncus erat vulputate tincidunt. Suspendisse fringilla, mauris ut sodales fringilla, mauris mauris volutpat nibh, id tempor metus magna eu nisi." +
"Suspendisse potenti. Curabitur malesuada ante ac erat semper blandit. Nunc varius efficitur lectus eu sagittis. Donec fermentum diam nec nulla tempor, sit amet auctor risus fermentum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ultricies nunc ac nunc tempus sollicitudin. Fusce pretium quam dolor. Phasellus vestibulum et ante molestie pellentesque. Integer elit massa, luctus non luctus vel, accumsan vitae justo. Maecenas venenatis dapibus semper. Fusce felis nisi, euismod in placerat sed, tincidunt quis ligula. Vivamus et eros vel augue facilisis sodales sit amet id tortor. Fusce eu sapien ac nunc pellentesque sagittis ut at velit. Proin efficitur pretium leo porttitor elementum. Aliquam lacus urna, semper vitae consequat a, finibus a purus." +
"Etiam mollis nibh tellus, non imperdiet nulla egestas id. Duis faucibus augue non dolor congue iaculis. Quisque et mi volutpat, aliquet sapien tempus, sagittis purus. Vestibulum non felis finibus, elementum nulla vitae, semper dui. Ut congue dolor eget tincidunt lacinia. Suspendisse condimentum est nec enim interdum, vel faucibus mi porttitor. Etiam gravida sapien ut velit pellentesque malesuada. Integer id elit eget nunc suscipit aliquet eu tristique urna. In laoreet magna quis hendrerit egestas. Phasellus facilisis, urna consectetur hendrerit auctor, augue magna pulvinar ipsum, quis euismod erat eros sit amet dui. Suspendisse mollis efficitur diam, ac consequat nibh rutrum in. Fusce posuere ullamcorper mattis. Proin sapien velit, efficitur non scelerisque id, iaculis nec purus. Vivamus quam turpis, rutrum nec commodo ut, venenatis sed eros. Fusce dolor arcu, egestas blandit metus ut, egestas tempor enim." +
"Vestibulum vehicula porta neque, non elementum purus tempus a. Phasellus nec ante vitae nulla rutrum commodo vel vel leo. Nullam et pellentesque ipsum. Nam laoreet nibh sed velit tempus condimentum. Duis aliquet, ligula vel pharetra vulputate, lacus leo pulvinar eros, eget dignissim metus ligula eleifend lectus. Pellentesque quis hendrerit elit. Nunc blandit mollis tellus, nec efficitur erat eleifend at. Vestibulum et consectetur leo. In auctor molestie leo, sed pretium odio sodales quis. Mauris molestie vehicula turpis non tristique. Interdum et malesuada fames ac ante ipsum primis in faucibus. Duis eget turpis at leo ornare congue sit amet in dolor. Nam lobortis leo iaculis tempor venenatis." +
"Nam egestas hendrerit tempor. Mauris egestas mi in lorem suscipit, ac rutrum nunc mollis. Praesent et nisi mollis, elementum sem eu, vehicula dolor. Sed et vulputate mi. Aenean sodales ante eu elit elementum vulputate. Donec hendrerit ligula at enim ornare, a imperdiet est condimentum. Maecenas tincidunt nisi mi, quis porttitor enim accumsan eu. Donec eget augue eu arcu pretium suscipit at ac ligula. Aenean sed luctus purus. Nunc luctus sem sit amet urna dignissim, sit amet venenatis neque rhoncus. Cras convallis vestibulum magna, at feugiat purus iaculis ac. Ut dignissim, ante sed vehicula consectetur, velit nunc consequat odio, eget tincidunt metus arcu in risus. Nulla volutpat non mi eget volutpat." +
"Fusce ut ante ut nisl semper eleifend non sed mauris. Nulla dictum consequat dolor ac elementum. Quisque et dui aliquet, cursus purus non, consectetur mauris. Sed eget viverra turpis. Sed posuere tincidunt est at efficitur. Curabitur vitae pharetra turpis, quis malesuada metus. Phasellus sed pretium felis, vitae fermentum dolor. Donec consectetur justo quis erat sagittis congue."
            }
        };

        public IEnumerable<Post> GetAllPosts()
        {
            return sqlDbImposter;
        }

        public Post GetPost(int chapter, int section)
        {
            return sqlDbImposter.FirstOrDefault(p => chapter == p.chapter && section == p.section);
        }
    }
}